import { Event } from './types';

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'City Park Cleanup Drive',
    organization: 'Green Earth Initiative',
    date: '2023-11-15',
    time: '09:00 AM',
    location: 'Central Park, Downtown',
    description: 'Join us for a morning of revitalizing our beloved Central Park. We will be collecting litter, planting new shrubs, and painting benches. Gloves and refreshments provided.',
    category: 'Environment',
    imageUrl: 'https://picsum.photos/id/10/800/600',
    spotsTotal: 50,
    spotsTaken: 32,
  },
  {
    id: 'e2',
    title: 'Tech Tutoring for Seniors',
    organization: 'Digital Bridges NGO',
    date: '2023-11-18',
    time: '02:00 PM',
    location: 'Community Library, Westside',
    description: 'Help seniors stay connected! We need patient volunteers to teach basic smartphone and computer skills. No advanced technical knowledge required, just a willingness to help.',
    category: 'Education',
    imageUrl: 'https://picsum.photos/id/20/800/600',
    spotsTotal: 15,
    spotsTaken: 12,
  },
  {
    id: 'e3',
    title: 'Food Bank Distribution',
    organization: 'Meals for All',
    date: '2023-11-20',
    time: '08:00 AM',
    location: 'Hope Center, North Hills',
    description: 'Assist in sorting and distributing food packages to families in need. Heavy lifting may be required. A great way to directly impact your local community.',
    category: 'Community',
    imageUrl: 'https://picsum.photos/id/30/800/600',
    spotsTotal: 40,
    spotsTaken: 10,
  },
  {
    id: 'e4',
    title: 'Animal Shelter Open Day',
    organization: 'Paws & Claws Rescue',
    date: '2023-11-25',
    time: '10:00 AM',
    location: 'Paws Shelter, East River',
    description: 'Spend the day walking dogs, socializing cats, and helping with general shelter maintenance. Perfect for animal lovers looking to give back.',
    category: 'Animals',
    imageUrl: 'https://picsum.photos/id/40/800/600',
    spotsTotal: 20,
    spotsTaken: 20,
  },
  {
    id: 'e5',
    title: 'Community Health Fair Support',
    organization: 'Red Cross Local Chapter',
    date: '2023-12-01',
    time: '08:30 AM',
    location: 'Convention Center',
    description: 'Support our annual health fair by guiding attendees, manning registration desks, and assisting medical professionals with logistics.',
    category: 'Health',
    imageUrl: 'https://picsum.photos/id/50/800/600',
    spotsTotal: 100,
    spotsTaken: 45,
  },
  {
    id: 'e6',
    title: 'Beach Conservation Workshop',
    organization: 'Ocean Guardians',
    date: '2023-12-05',
    time: '07:00 AM',
    location: 'Sunny Beach Pier',
    description: 'Learn about marine life and help clean up the shoreline. This event includes a workshop on sustainable living and plastic reduction.',
    category: 'Environment',
    imageUrl: 'https://picsum.photos/id/60/800/600',
    spotsTotal: 30,
    spotsTaken: 5,
  }
];

export const CATEGORY_COLORS: Record<string, string> = {
  Environment: 'bg-green-500/10 text-green-400 border-green-500/20',
  Education: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  Community: 'bg-alchemy-500/10 text-alchemy-400 border-alchemy-500/20',
  Health: 'bg-red-500/10 text-red-400 border-red-500/20',
  Animals: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
};
